name: SonoBus â€” Build on Linux

on:
  push:
    branches:
  pull_request:

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libfreetype-dev libopus-dev libasound2-dev libjack-jackd2-dev

      - name: Build
        run: |
          ./setupcmake.sh
          ./buildcmake.sh

      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3

