name: SonoBus â€” Build on Windows

on:
  push:
    branches: [ 1.7.4-gh-actions ]
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ASIO SDK
        run: git clone https://github.com/steinbergmedia/asiosdk.git C:\asiosdk

      - name: Configure Cmake
        run: cmake -S . -B build -DJUCE_ENABLE_STANDALONE_APPLICATION=ON -DJUCE_ASIO=ON -DJUCE_ASIO_SDK_PATH=C:\asiosdk

      - name: Build Standalone
        run: cmake --build build --config Release --target SonoBus

      # Find
      - name: Build
        shell: bash
        run: |
          ./find.sh

      # Upload Standalone and VST3
      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3

