name: Opus â€” Build on Windows

on:
  push:
    branches:
      - 1.7.4-gh-actions
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MSVC toolset
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup MSYS2 and install build tools
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS          # or MSYS or MINGW32 depending on your needs
          update: true            # run pacman -Syu (the action handles the restart dance)
          install: >
            base-devel
            autoconf
            automake
            gcc
            m4
            perl
            pkg-config
            libtool

      - name: Debug workspace & run make (MSYS2)
        shell: msys2 {0}
        run: |
          ./setupcmakewin.sh
          ./buildcmake.sh

      # Upload Standalone and VST3
      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3
