name: SonoBus â€” Build on Windows

on:
  push:
    branches: [ 1.7.4-gh-actions ]
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Cmake
        run: cmake -S . -B build -DJUCE_ENABLE_STANDALONE_APPLICATION:BOOL=ON -DJUCE_ASIO:BOOL=OFF

      - name: Dump CMake cache
        run: |
          findstr JUCE_ASIO build\CMakeCache.txt

      - name: Find
        shell: bash
        run: |
          ./find.sh

      - name: Build Standalone
        run: cmake --build build --config Release --target SonoBus


      # Upload Standalone and VST3
      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3

