name: SonoBus â€” Build on Windows

on:
  push:
    branches: [ 1.7.4-gh-actions ]
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake & Build
        run: >
          cmake -B build -S . 
          cmake --build build --config Release --target SonoBus_Standalone

      # Build
      - name: Build
        shell: bash
        run: |
          ./find.sh

      # Upload Standalone and VST3
      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3

