name: SonoBus â€” Build on Windows

on:
  push:
    branches:
  pull_request:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Cmake
        run: cmake -S . -B build -DJUCE_ENABLE_STANDALONE_APPLICATION:BOOL=ON -DJUCE_ASIO:BOOL=ON

      - name: Build Standalone
        run: |
          cmake --build build --config Release --target SonoBus_Standalone
          cmake --build build --config Release --target SonoBus_VST3

      - name: Upload Sonobus_artefacts
        uses: actions/upload-artifact@v4
        with:
          name: SonoBusMendeni-${{ runner.os }}
          path: |
             build/SonoBus_artefacts/Release/Standalone
             build/SonoBus_artefacts/Release/VST3

